classdef Constants
    properties (Constant)
        VersionString = 'v0.2.8';
        
        KeyboardShortcuts = {        ...
            'openVideoButton' 'o';   ...
            'toggleVideoButton' 'p'; ...
            'stopVideoButton' 'z';   ...
            'rewindButton' java.awt.event.KeyEvent.VK_LEFT;   ...
            'forwardButton' java.awt.event.KeyEvent.VK_RIGHT; ...
            
            'sceneColorButton' 'c';     ...
            'setSceneAreaButton' 'a';   ...
            'paintArenaButton' 'h';     ...
            'startTrackingButton' 't';  ...
            'trackingResultsButton' 's' ...
        };
        
        VideoSpeedLimit = 10;
        
        CircleOnBlankRadius = 10;
        CircleOnBlankFrameSkip = 1;
        
        CircleOnVideoColors = [ ...
          0 0 255;     ...
          0 255 0;     ...
          255 255 0;   ...
          255 0 255;   ...
          0 255 255;   ...
          255 255 255; ...
          0 0 0;       ...
          255 0 0;     ...
        ];
        
        CircleOnBlankColors = [ ...
          0 0 0;       ...
          100 100 100; ...
          255 0 0;     ...
          0 0 255;     ...
          0 255 0;     ...
          255 255 0;   ...
          255 0 255;   ...
          0 255 255;   ...
          255 255 255  ...
        ];
    
        LostSubjectColor = [255 0 0];
        ExcludedAreaColor = [0 40 0];
        SceneFrameColor = [0 100 0];
        SceneMarkerColor = [0 100 0];
        SceneMarkerRadius = 6;
    
        DisplayFrameRate = 100;
        DisplayTrackingFrameRate = 100;
        
        MinimumNumberPoints = 5;
        RadiusGrowthRate = 0.1;
        
        BufferedVideoWindow = 100;
    end
end
